import { test, expect } from '@playwright/test'

test('desktop and mobile discovery, filters, navigation and basket', async ({ page }) => {
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/')
 await expect(page.getByRole('heading', {name:'Find your kind of food.'})).toBeVisible()
 await expect(page.locator('.discovery-card')).toHaveCount(7)
 await page.locator('.discovery-collage img').evaluateAll(images => Promise.all(images.map(img => img.decode().catch(() => {}))))
 await page.screenshot({path:'test-results/home-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Seafood',exact:true}).click()
 await expect(page.locator('.discovery-card')).toHaveCount(1)
 await page.getByRole('button',{name:'All food',exact:true}).click()
 await expect(page.locator('.discovery-card')).toHaveCount(7)
 await page.getByRole('button',{name:'Cart',exact:true}).click()
 await expect(page.getByText('Your basket is waiting')).toBeVisible()
 await page.getByRole('button',{name:'Close',exact:true}).click()
 await page.setViewportSize({width:390,height:844})
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'test-results/home-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
 await page.getByRole('button',{name:'Toggle navigation'}).click()
 await page.getByRole('link',{name:'Start selling',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Good things start with your business.'})).toBeVisible()
 expect(errors).toEqual([])
})

test('restaurant signup opens dashboard and all restaurant screens', async ({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/register')
 await page.getByRole('button',{name:'Continue'}).click()
 await page.getByLabel('Owner name').fill('Browser Owner')
 await page.getByLabel('Email',{exact:true}).fill(`browser-${Date.now()}@example.test`)
 await page.getByLabel('Password').fill('Browser-password-2026')
 await page.getByLabel('Restaurant name').fill('Browser Test Kitchen')
 await page.getByLabel('Phone',{exact:true}).fill('+2348001234567')
 await page.getByLabel('Address',{exact:true}).fill('Lagos')
 await page.screenshot({path:'test-results/register-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Create account',exact:true}).click()
 await expect(page).toHaveURL(/dashboard$/)
 await expect(page.getByRole('heading',{name:'Browser Test Kitchen'})).toBeVisible()
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true})
 for(const path of ['/menu-builder','/orders','/kitchen','/analytics','/qr-code','/subscriptions','/settings']) {
  await page.goto(path)
  await expect(page.locator('main h1').first()).toBeVisible()
  await expect(page.getByText('Something went wrong')).toHaveCount(0)
 }
 await page.setViewportSize({width:390,height:844})
 await page.goto('/dashboard')
 await expect(page.getByRole('heading',{name:'Browser Test Kitchen'})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
 await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true})
 expect(errors).toEqual([])
})

test('menu to checkout persists a real order and clears basket',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/menu/8am-light-kitchen')
 await expect(page.getByRole('button',{name:'Add to cart'}).first()).toBeVisible()
 await page.getByRole('button',{name:'Add to cart'}).first().click()
 await page.screenshot({path:'test-results/menu-desktop.png',fullPage:true})
 await page.getByRole('link',{name:'Checkout',exact:true}).click()
 await page.getByLabel('Name',{exact:true}).fill('Browser Customer')
 await page.getByLabel('Phone',{exact:true}).fill('08001234567')
 await page.getByRole('button',{name:'Place order'}).click()
 await expect(page.getByText('Order created',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Confirm on WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa.me\//)
 expect(await page.evaluate(()=>localStorage.getItem('raviMenuCart:8am-light-kitchen'))).toBeNull()
 expect(errors).toEqual([])
})

test('API outage and unknown menus show recoverable errors',async({page})=>{
 await page.route('**/api/public/restaurants*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Temporarily unavailable'})}))
 await page.goto('/')
 await expect(page.getByRole('button',{name:'Try again',exact:true})).toBeVisible()
 await expect(page.locator('.discovery-card')).toHaveCount(0)
 await page.goto('/menu/not-a-real-restaurant')
 await expect(page.getByRole('heading',{name:'Menu unavailable'})).toBeVisible()
})
